name: CI-ML-Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # (Optionnel) Télécharger les données si absentes
      - name: Load data
        run: python src/load_data.py

      # Prétraitement
      - name: Preprocess data
        run: python src/preprocess.py

      # Entraînement — crée models/*.joblib
      - name: Train models
        run: python src/train.py

      # ✅ Évaluation (ne sera plus en erreur)
      - name: Evaluate models
        run: python src/evaluate.py

      # Sauvegarde des résultats MLflow
      - name: Upload MLflow results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-results
          path: mlruns/
