name: CI-ML-Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Force MLflow à écrire en local dans ./mlruns
      MLFLOW_TRACKING_URI: file:./mlruns

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure dirs exist
        run: |
          mkdir -p mlruns
          mkdir -p results
          mkdir -p models

      - name: Load data
        run: python src/load_data.py

      - name: Preprocess data
        run: python src/preprocess.py

      - name: Train models
        run: python src/train.py

      - name: Evaluate models (writes results/*.csv & *.json)
        run: python src/evaluate.py

      - name: Upload artifacts (MLflow + results + models)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-results
          path: |
            mlruns/
            results/
            models/
          if-no-files-found: warn
