name: CI-ML-Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Télécharge les données si absentes (voir étape 3)
      - name: Load data
        run: python src/load_data.py

      - name: Preprocess
        run: python src/preprocess.py

      - name: Train
        run: python src/train.py

      - name: Evaluate
        run: python src/evaluate.py

      - name: Upload MLflow runs as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-results
          path: mlruns/
